### ISSUE TITLE
Error in ExtractROI during low-resolution registration

### ISSUE THREAD

**Issue by brandon-gallas** [DIDSR/eeDAP#31] opened 2017-06-16 00:04 UTC
The location I selected was near the boundary and I got the error below. The process shouldn't cause an error. I should be allowed to select another registration location, not so close to the boundary.

Error in ExtractROI: Illegal Extraction Origin Left or Top, ExtractHeight or ExtractWidth
Origin Left = -113.2128                                                                  
Origin Top = 11059.5154                                                                  
InputWidth = 1654.0152                                                                   
InputHeight = 1654.0152                                                                  
OutputWidth = 300                                                                        
OutputHeight = 300

**Comment by qigongFDA** [comment] 2017-06-27 19:06
I increase the checking limitation about ROI goes out from WSI. I think the problem is solved. But user can't choose position very close to boundary.  Can we close this?

**Comment by qigongFDA** [comment] 2017-06-27 19:38
Fixed

**Closed by qigongFDA** 2017-06-27 19:38 UTC
