### ISSUE TITLE
Provide image name and thumbnail of slide being registered 

### ISSUE THREAD

**Issue by brandon-gallas** [DIDSR/eeDAP#39] opened 2017-06-26 14:15 UTC

**Comment by qigongFDA** [comment] 2017-07-18 18:50
The image name and thumbnail have been added to global registration interface. Can we close this issue?

**Comment by qigongFDA** [comment] 2017-07-18 20:05
Brandon says the issue is completed.

**Comment by brandon-gallas** [comment] 2017-11-13 21:52
Can we add the slide label too, if it exists?

**Comment by qigongFDA** [comment] 2017-11-13 22:25
For now, The image name is the main information in label. We don't have to add label. I talked with Brandon. We decide to close this issue for now.

**Closed by qigongFDA** 2017-11-13 22:25 UTC
Labels: 3-Weeks
